# =============================================================================
# Training Configuration
# =============================================================================

# Default Training settings
batch_size: 56
epochs: 300
num_workers: 0
learning_rate: 1e-3
weight_decay: 1e-4
train_tag: 'default'

# =============================================================================
# Data Configuration
# =============================================================================

# Data paths
data_train_path: 'src/data/split/train'
data_val_path: 'src/data/split/val'
data_test_path: 'src/data/split/test'
data_patch_path: 'patches'

# =============================================================================
# Model Configuration
# =============================================================================

# Model options:
#   1. lr             : Linear Regressor
#   2. svr            : Support Vector Regressor
#   3. ann            : Artificial Neural Network (Simple DNN)
#   4. cnn_1d_scirep  : 1D-CNN (Taye et al.)
#   5. cnn_1d_4ha     : 1D-CNN (Hassan et al.)
#   6. cnn_1d_generic : Simple 1D-CNN for comparing with proposed model
#   7. transformer    : Proposed Transformer Regressor 
#   8. gated_mlp      : Proposed Gated Fusion MLP
model: transformer
